// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwqbdhtnimvfoxzyisgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13cWJkaHRuaW12Zm94enlpc2d5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMzAzODAsImV4cCI6MjA3MTkwNjM4MH0.-ZuHnJKMNwmIkb-gCufbK66oUPUEZsDRvDjyCv7IZis";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});